name: flutter_coverage_badge
description: Flutter Coverage Badge
version: 1.0.0
homepage: https://github.com/fernandomoraesvr/flutter_coverage_badge

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'
executables:
  flutter_coverage_badge:

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  glob: ^2.0.1
  args: ^2.3.0
  lcov_dart: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: